name: Contexto
run-name: ¡Estoy aprendiendo a usar Contextos!
on: push
jobs:
  check-main:
    # condiciones para ejecutar el job
    # si la rama es main realiza el job
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"